### ISSUE TITLE
Feat: 칼로리 API 구현

### ISSUE THREAD

**Issue by zzimnii** [Yorieter/UMC-Yorieter_BE#38]
## 📌 Feature Issue
OpenAPI 활용하여 칼로리 검색 구현

## 📝 To-do
- [x] OpenAPI 활용하여 칼로리 검색 구현
- [x] 칼로리 무게 비례 저장
- [x] 식재료 수정
- [x] 식재료 수정시 recipe_ingredient 삭제

## ETC
>
